import { getFavicon } from "@/lib/getFavicon";

export const gridData = [
	{
		id: 1,
		name: "Workbook - Testing design Ideas for grid and workbook",
		iconType: "multi" as const,
		icon: null,
		icons: [
			getFavicon("linkedin.com"),
			getFavicon("hubspot.com"),
			getFavicon("google.com"),
		],
		starred: false,
		isGroup: true,
		editedBy: {
			name: "Sam Taylor",
			avatar: "https://randomuser.me/api/portraits/men/32.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 2,
		name: "LinkedIn",
		icon: getFavicon("linkedin.com"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Chris Parker",
			avatar: "https://randomuser.me/api/portraits/women/44.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 3,
		name: "Sales nav",
		icon: getFavicon("linkedin.com"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 4,
		name: "find company",
		icon: getFavicon("google.com"),
		iconType: "single" as const,
		icons: null,
		starred: true,
		isGroup: false,
		editedBy: {
			name: "Alex Morgan",
			avatar: "https://randomuser.me/api/portraits/men/75.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 5,
		name: "import csv",
		icon: getFavicon("notion.so"),
		iconType: "single" as const,
		icons: null,
		starred: true,
		isGroup: false,
		editedBy: {
			name: "Drew Wilson",
			avatar: "https://randomuser.me/api/portraits/women/89.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 6,
		name: "Find people",
		icon: getFavicon("linkedin.com"),
		iconType: "single" as const,
		icons: null,
		starred: true,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 7,
		name: "Google maps",
		icon: getFavicon("maps.google.com"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 8,
		name: "google search results",
		icon: getFavicon("google.com"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 9,
		name: "factors",
		icon: getFavicon("factors.ai"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 10,
		name: "Hubspot List - 10 (05 Aug 25)",
		icon: getFavicon("hubspot.com"),
		iconType: "single" as const,
		icons: null,
		starred: true,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "06 Aug, 2025",
	},
	{
		id: 11,
		name: "Apollo contacts",
		icon: getFavicon("apollo.io"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Mark Spencer",
			avatar: "https://randomuser.me/api/portraits/men/45.jpg",
		},
		lastEdited: "05 Aug, 2025",
	},
	{
		id: 12,
		name: "Twitter leads",
		icon: getFavicon("x.com"),
		iconType: "single" as const,
		icons: null,
		starred: true,
		isGroup: false,
		editedBy: {
			name: "Sara Lee",
			avatar: "https://randomuser.me/api/portraits/women/22.jpg",
		},
		lastEdited: "05 Aug, 2025",
	},
	{
		id: 13,
		name: "Clearbit enrichment",
		icon: getFavicon("clearbit.com"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Tom Hardy",
			avatar: "https://randomuser.me/api/portraits/men/61.jpg",
		},
		lastEdited: "04 Aug, 2025",
	},
	{
		id: 14,
		name: "ZoomInfo export",
		icon: getFavicon("zoominfo.com"),
		iconType: "single" as const,
		icons: null,
		starred: false,
		isGroup: false,
		editedBy: {
			name: "Nina Roy",
			avatar: "https://randomuser.me/api/portraits/women/55.jpg",
		},
		lastEdited: "04 Aug, 2025",
	},
	{
		id: 15,
		name: "Outreach sequences",
		icon: getFavicon("outreach.io"),
		iconType: "single" as const,
		icons: null,
		starred: true,
		isGroup: false,
		editedBy: {
			name: "Jone Doe",
			avatar: "https://randomuser.me/api/portraits/women/68.jpg",
		},
		lastEdited: "03 Aug, 2025",
	},
];
