import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";

const inter = Inter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.className} h-full antialiased w-full`}
		>
			<body className="min-h-screen flex w-full">
				<Sidebar />
				<div className="flex flex-col flex-1 min-w-0">
					<Navbar />
					<main className="flex-1">{children}</main>
				</div>
			</body>
		</html>
	);
}
